/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FeedList: typeof import('./src/components/FeedList.vue')['default']
    PreviewModal: typeof import('./src/components/PreviewModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_embla-carousel@8.6.0_typescript@5.8.3_vite@5.4.19_lightni_myyysz6iqd7a562cdkevol6ljq/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_embla-carousel@8.6.0_typescript@5.8.3_vite@5.4.19_lightni_myyysz6iqd7a562cdkevol6ljq/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_embla-carousel@8.6.0_typescript@5.8.3_vite@5.4.19_lightni_myyysz6iqd7a562cdkevol6ljq/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_embla-carousel@8.6.0_typescript@5.8.3_vite@5.4.19_lightni_myyysz6iqd7a562cdkevol6ljq/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  }
}
